# Generated by Django 3.2.25 on 2025-05-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', '管理员'), ('user', '普通用户')], default='admin', max_length=10),
        ),
    ]
