# Generated by Django 3.2.25 on 2025-05-14 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guarantees', models.TextField(blank=True, default='无', null=True, verbose_name='纳税担保')),
                ('freezing', models.TextField(blank=True, default='无', null=True, verbose_name='冻结')),
                ('seizures', models.TextField(blank=True, default='无', null=True, verbose_name='查封、扣押')),
                ('reminders', models.TextField(blank=True, default='无', null=True, verbose_name='催告')),
                ('forced_collection', models.TextField(blank=True, default='无', null=True, verbose_name='强制扣缴（金额）')),
                ('auction', models.TextField(blank=True, default='无', null=True, verbose_name='拍卖、变卖（金额）')),
                ('court_execution', models.TextField(blank=True, default='无', null=True, verbose_name='申请人民法院强制执行')),
                ('rights_exercise', models.TextField(blank=True, default='无', null=True, verbose_name='行使代位权、撤销权')),
                ('exit_prevention', models.TextField(blank=True, default='无', null=True, verbose_name='阻止出境')),
                ('prohibited_departure', models.CharField(blank=True, default='无', max_length=255, null=True, verbose_name='限制出境信息')),
            ],
            options={
                'verbose_name': '欠税追征',
                'verbose_name_plural': '欠税追征',
            },
        ),
        migrations.CreateModel(
            name='DailyManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reminders', models.TextField(blank=True, null=True, verbose_name='催缴提醒文书')),
                ('invoice_control', models.CharField(blank=True, choices=[('未控票', '未控票'), ('控票中', '控票中'), ('数电票已限额', '数电票已限额'), ('拟列入', '拟列入'), ('限量供应', '限量供应'), ('停止控票', '停止控票'), ('暂停控票', '暂停控票')], default='未控票', max_length=20, null=True, verbose_name='发票管控')),
            ],
            options={
                'verbose_name': '日常管理',
                'verbose_name_plural': '日常管理',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('has_interview', models.BooleanField(blank=True, choices=[(True, '是'), (False, '否')], default=False, null=True, verbose_name='是否约谈')),
                ('document', models.CharField(blank=True, max_length=255, null=True, verbose_name='约谈文书或填写未约谈原因')),
                ('interview_date', models.DateField(blank=True, null=True, verbose_name='约谈时间')),
            ],
            options={
                'verbose_name': '约谈警示',
                'verbose_name_plural': '约谈警示',
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.CharField(blank=True, max_length=255, null=True, verbose_name='提醒文书')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='送达时间')),
            ],
            options={
                'verbose_name': '风险提醒',
                'verbose_name_plural': '风险提醒',
            },
        ),
        migrations.CreateModel(
            name='TaxForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('month', models.CharField(blank=True, default='202505', max_length=6, null=True, verbose_name='月度')),
                ('taxpayer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='纳税人名称')),
                ('credit_code', models.CharField(blank=True, max_length=18, null=True, verbose_name='统一社会信用代码')),
                ('taxpayer_status', models.CharField(blank=True, choices=[('正常', '正常'), ('⾮正常', '⾮正常'), ('注销', '注销'), ('非正常注销', '非正常注销'), ('报验', '报验'), ('核销报验', '核销报验')], default='正常', max_length=20, null=True, verbose_name='纳税人状态')),
                ('industry', models.CharField(blank=True, max_length=255, null=True, verbose_name='所属行业')),
                ('tax_authority_code', models.CharField(blank=True, max_length=11, null=True, verbose_name='主管税务机关代码')),
                ('tax_authority_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='主管税务所名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('status', models.CharField(blank=True, choices=[('draft', '草稿'), ('assigned', '已分配'), ('submitted', '已提交'), ('approved', '已审批')], default='draft', max_length=10, null=True, verbose_name='表单状态')),
            ],
            options={
                'verbose_name': '税务表单',
                'verbose_name_plural': '税务表单',
            },
        ),
        migrations.CreateModel(
            name='TaxPaymentWithAssets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='无', null=True, verbose_name='抵缴欠税情况描述')),
                ('tax_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_payment_with_assets', to='tax_forms.taxform', verbose_name='关联的税务表单')),
            ],
            options={
                'verbose_name': '抵缴欠税情况',
                'verbose_name_plural': '抵缴欠税情况',
            },
        ),
        migrations.CreateModel(
            name='TaxPaymentPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('has_agreement', models.BooleanField(blank=True, choices=[(True, '是'), (False, '否')], default=False, null=True, verbose_name='有无订立')),
                ('month_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='分期情况')),
                ('current_execution', models.CharField(blank=True, default='0', max_length=255, null=True, verbose_name='本期执行情况')),
                ('unfulfilled_reason', models.TextField(blank=True, default='无', null=True, verbose_name='未按期履行原因')),
                ('daily_management', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_payment_plan', to='tax_forms.dailymanagement', verbose_name='关联的日常管理')),
            ],
            options={
                'verbose_name': '清缴欠税计划',
                'verbose_name_plural': '清缴欠税计划',
            },
        ),
        migrations.CreateModel(
            name='TaxpayerReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periodic_report', models.TextField(blank=True, default='无', null=True, verbose_name='定期报告')),
                ('asset_disposal_report', models.TextField(blank=True, default='无', null=True, verbose_name='处置资产报告')),
                ('merger_division_report', models.TextField(blank=True, default='无', null=True, verbose_name='合并分立报告')),
                ('daily_management', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taxpayer_report', to='tax_forms.dailymanagement', verbose_name='关联的日常管理')),
            ],
            options={
                'verbose_name': '欠税人报告事项',
                'verbose_name_plural': '欠税人报告事项',
            },
        ),
        migrations.CreateModel(
            name='TaxpayerAssets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_accounts', models.TextField(blank=True, default='无', null=True, verbose_name='存款账户情况')),
                ('real_estate', models.TextField(blank=True, default='无', null=True, verbose_name='不动产信息')),
                ('vehicles', models.TextField(blank=True, default='无', null=True, verbose_name='机动车（船舶）信息')),
                ('other_assets', models.TextField(blank=True, default='无', null=True, verbose_name='其他资产信息')),
                ('daily_management', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taxpayer_assets', to='tax_forms.dailymanagement', verbose_name='关联的日常管理')),
            ],
            options={
                'verbose_name': '纳税人资产情况',
                'verbose_name_plural': '纳税人资产情况',
            },
        ),
        migrations.CreateModel(
            name='TaxInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('outstanding_tax', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='截至目前欠缴税费情况')),
                ('tax_types', models.TextField(blank=True, null=True, verbose_name='涉及税费种')),
                ('collection_effect', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='清欠成效')),
                ('tax_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_info', to='tax_forms.taxform', verbose_name='关联的税务表单')),
            ],
            options={
                'verbose_name': '欠税信息',
                'verbose_name_plural': '欠税信息',
            },
        ),
        migrations.AddIndex(
            model_name='taxform',
            index=models.Index(fields=['credit_code'], name='tax_forms_t_credit__0baf36_idx'),
        ),
        migrations.AddIndex(
            model_name='taxform',
            index=models.Index(fields=['month'], name='tax_forms_t_month_768762_idx'),
        ),
        migrations.AddIndex(
            model_name='taxform',
            index=models.Index(fields=['taxpayer_name'], name='tax_forms_t_taxpaye_a4b7b0_idx'),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='daily_management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='tax_forms.dailymanagement', verbose_name='关联的日常管理'),
        ),
        migrations.AddField(
            model_name='interview',
            name='daily_management',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='tax_forms.dailymanagement', verbose_name='关联的日常管理'),
        ),
        migrations.AddField(
            model_name='dailymanagement',
            name='tax_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_management', to='tax_forms.taxform', verbose_name='关联的税务表单'),
        ),
        migrations.AddField(
            model_name='collection',
            name='tax_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='tax_forms.taxform', verbose_name='关联的税务表单'),
        ),
    ]
